services:
  - type: web
    name: saeb
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12 # Garante que a versão do Python é a correta
    disks:
      - name: database
        mountPath: /var/data
        sizeGB: 1